export type KeywordTarget = string;

export const KEYWORDS: Record<string, KeywordTarget> = {
    // English
    "data": "data",
    "hash": "hashing",
    "hashes": "hashing",
    "prev hash": "chain",
    "nonce": "mining",
    "nonces": "mining",
    "proof of work": "mining",
    "mining": "mining",
    "miner": "mempool",
    "miners": "mempool",
    "block": "block",
    "blocks": "block",
    "chain": "chain",
    "chains": "chain",
    "blockchain": "chain",
    "blockchains": "chain",
    "node": "network",
    "nodes": "network",
    "wallet": "keys",
    "wallets": "keys",
    "private key": "keys",
    "private keys": "keys",
    "public key": "keys",
    "public keys": "keys",
    "message": "keys",
    "messages": "keys",
    "signature": "keys",
    "signatures": "keys",
    "transaction hash": "transactions",
    "transaction hashes": "transactions",
    "transaction": "transactions",
    "transactions": "transactions",
    "mempool": "mempool",
    "fee": "mempool",
    "fees": "mempool",
    "network": "network",
    "determinism": "determinism",
    "validity": "validity",
    "data validity": "validity",

    // Russian
    "данных": "data",
    "данные": "data",
    "данными": "data",
    "хеш": "hashing",
    "хеша": "hashing",
    "хеши": "hashing",
    "майнинг": "mining",
    "майнинга": "mining",
    "блок": "block",
    "блока": "block",
    "блоки": "block",
    "блоков": "block",
    "цепь": "chain",
    "цепи": "chain",
    "цепочка": "chain",
    "блокчейн": "chain",
    "узлов": "network",
    "узлы": "network",
    "узел": "network",
    "узла": "network",
    "кошелек": "keys",
    "кошелька": "keys",
    "кошельки": "keys",
    "кошельков": "keys",
    "приватный ключ": "keys",
    "приватные ключи": "keys",
    "приватного ключа": "keys",
    "публичный ключ": "keys",
    "публичные ключи": "keys",
    "публичного ключа": "keys",
    "подпись": "keys",
    "подписи": "keys",
    "подписью": "keys",
    "мемпул": "mempool",
    "мемпула": "mempool",
    "транзакция": "transactions",
    "транзакции": "transactions",
    "транзакций": "transactions",
    "сеть": "network",
    "сети": "network",
    "детерминизм": "determinism",
    "валидность": "validity",
} as const;
